/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const HealthStatus = {
  OK: 'OK',
  WARN: 'WARN',
  ERROR: 'ERROR'
} as const

export type HealthStatus = (typeof HealthStatus)[keyof typeof HealthStatus]
