import { z } from 'zod';

export const PERMISSION = [
  'SUPERUSER_CREATE',
  'SUPERUSER_UPDATE',
  'SUPERUSER_DELETE',
  'USER_CREATE',
  'USER_UPDATE',
  'USER_DELETE',
  'USER_ROLE_CREATE',
  'USER_ROLE_UPDATE',
  'USER_ROLE_DELETE',
  'ROLE_CREATE',
  'ROLE_UPDATE',
  'ROLE_DELETE',
  'GROUP_CREATE',
  'GROUP_UPDATE',
  'GROUP_DELETE',
  'SERVICE_CREATE',
  'SERVICE_UPDATE',
  'SERVICE_DELETE',
  'MIDDLEWARE_CREATE',
  'MIDDLEWARE_UPDATE',
  'MIDDLEWARE_DELETE',
  'SERVICE_APIKEYS_CREATE',
  'SERVICE_APIKEYS_UPDATE',
] as const;

export const PermissionSchema = z.enum(PERMISSION);

export type Permission = z.infer<typeof PermissionSchema>;
