import type { Prisma } from '../dsrc/client';
import { z } from 'zod';
import { AccountEmailVerificationOrderByWithRelationInputObjectSchema as AccountEmailVerificationOrderByWithRelationInputObjectSchema } from './objects/account-email-verification-AccountEmailVerificationOrderByWithRelationInput-input.js';
import { AccountEmailVerificationWhereInputObjectSchema as AccountEmailVerificationWhereInputObjectSchema } from './objects/account-email-verification-AccountEmailVerificationWhereInput-input.js';
import { AccountEmailVerificationWhereUniqueInputObjectSchema as AccountEmailVerificationWhereUniqueInputObjectSchema } from './objects/account-email-verification-AccountEmailVerificationWhereUniqueInput-input.js';
import { AccountEmailVerificationCountAggregateInputObjectSchema as AccountEmailVerificationCountAggregateInputObjectSchema } from './objects/account-email-verification-AccountEmailVerificationCountAggregateInput-input.js';
import { AccountEmailVerificationMinAggregateInputObjectSchema as AccountEmailVerificationMinAggregateInputObjectSchema } from './objects/account-email-verification-AccountEmailVerificationMinAggregateInput-input.js';
import { AccountEmailVerificationMaxAggregateInputObjectSchema as AccountEmailVerificationMaxAggregateInputObjectSchema } from './objects/account-email-verification-AccountEmailVerificationMaxAggregateInput-input.js';

export const AccountEmailVerificationAggregateSchema: z.ZodType<Prisma.AccountEmailVerificationAggregateArgs> = z.object({ orderBy: z.union([AccountEmailVerificationOrderByWithRelationInputObjectSchema, AccountEmailVerificationOrderByWithRelationInputObjectSchema.array()]).optional(), where: AccountEmailVerificationWhereInputObjectSchema.optional(), cursor: AccountEmailVerificationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AccountEmailVerificationCountAggregateInputObjectSchema ]).optional(), _min: AccountEmailVerificationMinAggregateInputObjectSchema.optional(), _max: AccountEmailVerificationMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AccountEmailVerificationAggregateArgs>;

export const AccountEmailVerificationAggregateSchemaZodSchema = z.object({ orderBy: z.union([AccountEmailVerificationOrderByWithRelationInputObjectSchema, AccountEmailVerificationOrderByWithRelationInputObjectSchema.array()]).optional(), where: AccountEmailVerificationWhereInputObjectSchema.optional(), cursor: AccountEmailVerificationWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AccountEmailVerificationCountAggregateInputObjectSchema ]).optional(), _min: AccountEmailVerificationMinAggregateInputObjectSchema.optional(), _max: AccountEmailVerificationMaxAggregateInputObjectSchema.optional() }).strict();